/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingSol from "./Staking.sol";
export type { stakingSol };
export type { ERC20 } from "./ERC20";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IUniswapV2Factory__factory } from "./factories/IUniswapV2Factory__factory";
export { IUniswapV2Pair__factory } from "./factories/IUniswapV2Pair__factory";
export { IUniswapV2Router01__factory } from "./factories/IUniswapV2Router01__factory";
export { IUniswapV2Router02__factory } from "./factories/IUniswapV2Router02__factory";
export type { IERC20 } from "./Staking.sol/IERC20";
export { IERC20__factory } from "./factories/Staking.sol/IERC20__factory";
export type { Staking } from "./Staking.sol/Staking";
export { Staking__factory } from "./factories/Staking.sol/Staking__factory";
